services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-vector
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: unless-stopped
  valkey:
    #image: valkey/valkey-bundle:latest
    image: redis/redis-stack:latest
    container_name: valkey-memory
    volumes:
     # - ./valkey_data:/data
      - ./redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped